version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - TZ=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=*
    volumes:
      # gunakan path absolut agar Windows tidak bingung
      - C:\Users\Syahri Ramadhan\Documents\Projects\n8n\data:/home/node/.n8n
      - C:\Users\Syahri Ramadhan\Documents\Projects\n8n\scripts:/scripts
